import toml
import re
import os


def update_project_toml(export_file, project_toml_file, requirements_file):
    """Updates the pyproject.toml file with dependency versions from an export file and creates requirements.txt.

    Args:
        export_file (str): Path to the file generated by 'poetry export --with-hashes'.
        project_toml_file (str): Path to the pyproject.toml file.
        requirements_file (str): Path to the requirements.txt file to be created.
    """

    if not os.path.exists(export_file):
        print(
            f"Error: '{export_file}' not found. Please run 'poetry export --with-hashes -f {export_file}' first."
        )
        return

    if not os.path.exists(project_toml_file):
        print(f"Error: '{project_toml_file}' not found.")
        return

    with open(export_file, 'r') as f:
        export_data = f.readlines()

    # Extract package name and version from the export file
    dependencies = {}
    for line in export_data:
        # Match the format of poetry export --with-hashes
        match = re.match(
            r'^(?P<package_name>\w+)\s*=\s*(?P<version>[^#\s]+)\s*$', line)
        if match:
            dependencies[match.group('package_name')] = match.group('version')

    with open(project_toml_file, 'r') as f:
        project_toml = toml.load(f)

    # Update the dependencies in project.toml
    for key, value in dependencies.items():
        if key in project_toml['tool']['poetry']['dependencies']:
            # Preserve existing formatting
            project_toml['tool']['poetry']['dependencies'][key] = value

    # Write the updated project.toml file
    with open(project_toml_file, 'w') as f:
        toml.dump(project_toml, f)

    # Create requirements.txt
    with open(requirements_file, 'w') as f:
        for key, value in dependencies.items():
            f.write(f"{key}=={value}\n")


if __name__ == '__main__':
    export_file = 'poetry.lock'
    project_toml_file = 'pyproject.toml'
    requirements_file = 'requirements.txt'
    update_project_toml(export_file, project_toml_file, requirements_file)
    print(
        f"Updated {project_toml_file} with dependency versions from {export_file}"
    )
    print(f"Created {requirements_file}")
